version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::488072358542:user/aws-sam-cli-managed-dev-env-pipeline-r-PipelineUser-Aj8KmJbzEZp7"
permissions_provider = "AWS IAM"

[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::488072358542:role/aws-sam-cli-managed-dev-env-p-PipelineExecutionRole-YhtGAosRYyRu"
cloudformation_execution_role = "arn:aws:iam::488072358542:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionRo-rH1lVzqxEKBR"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-frkj1k9qto29"
image_repository = ""
region = "us-east-1"

[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::488072358542:role/aws-sam-cli-managed-prod-env--PipelineExecutionRole-pFYVMHQh1REn"
cloudformation_execution_role = "arn:aws:iam::488072358542:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-pM6LcW5QnH9C"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-tpgct24f8q3r"
image_repository = ""
region = "us-east-1"
